title: NSLog("Life & Code");
subtitle: null
description: 整理开发中遇到的问题与平时的一些技术积累，希望在备忘的同时能对别人有帮助
keywords: iOS,Laravel,Ruby on Rails,React Native,Mac, Linux, Life
author: welsonla
language: zh-Hans
timezone: ''
url: http://welsonla.timebot.net
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':year-:month-:day-:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
prism_plugin:
  mode: preprocess
  theme: default
  line_number: true
highlight:
  enable: true
prismjs:
  enable: false
default_category: uncategorized
category_map: null
tag_map: null
index_generator:
  path: ''
  per_page: 20
  order_by: '-date'
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 20
pagination_dir: page
ga_track_id: G-J8R1NG8CX8
theme: icarus
since: 2013
disqus_shortname: welsonlablog
deploy:
  type: git
  repo: git@github.com:welsonla/welsonla.github.com.git
  branch: master
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
browsersync:
  logLevel: warn
  ghostMode:
    scroll: true
  instanceName: uniqueString
