widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

logo: /uploads/avatar.jpg
rss: /atom.xml
disqus: welsonla
google_analytics: UA-19152389-6

# Social accounts
instagram: welsonla
pinterest:
github: welsonla
facebook:
twitter: welsonla
linkedin: 